/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FilmEpisodeLazyImport = createFileRoute('/film/$episode')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FilmEpisodeLazyRoute = FilmEpisodeLazyImport.update({
  path: '/film/$episode',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/film.$episode.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/film/$episode': {
      id: '/film/$episode'
      path: '/film/$episode'
      fullPath: '/film/$episode'
      preLoaderRoute: typeof FilmEpisodeLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FilmEpisodeLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/film/$episode"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/film/$episode": {
      "filePath": "film.$episode.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
